separate steps for eslint 3

diff --git a/.github/workflows/webpack.yml b/.github/workflows/webpack.yml
--- a/.github/workflows/webpack.yml
+++ b/.github/workflows/webpack.yml
@@ -1,8 +1,10 @@
+name: NodeJS with Webpack
+
 on:
   push:
-    branches: ["main"]
+    branches: [ "main" ]
   pull_request:
-    branches: ["main"]
+    branches: [ "main" ]
 
 jobs:
   eslint:
@@ -23,21 +25,21 @@ jobs:
           npm install
           npm install @eslint/eslintrc @typescript-eslint/parser @typescript-eslint/eslint-plugin  # Ensure TypeScript ESLint plugins are installed if needed
 
-      - name: Run ESLint and Generate SARIF Report
+      - name: Run ESLint and Generate Report
         run: |
-          npx eslint . -f sarif -o eslint-report.sarif || true  # Always return success
+          npx eslint . -f json -o eslint-report.json || true  # Always return success
         continue-on-error: true
 
-      - name: Upload ESLint SARIF Report
-        uses: github/codeql-action/upload-sarif@v2
-        with:
-          sarif_file: eslint-report.sarif
-
-      - name: Upload ESLint Report as Artifact
+      - name: Run ESLint 
+        run: | 
+          npx eslint . || true  # Prevent ESLint errors from failing the step
+        continue-on-error: true  # Ensure the job continues even if ESLint finds errors
+          
+      - name: Upload ESLint Report
         uses: actions/upload-artifact@v3
         with:
           name: eslint-report
-          path: eslint-report.sarif
+          path: eslint-report.json
           if-no-files-found: ignore
           include-hidden-files: false
 
@@ -51,19 +53,18 @@ jobs:
         node-version: [18.x, 20.x, 22.x]
 
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+    - uses: actions/checkout@v4
 
-      - name: Set Up Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ matrix.node-version }}
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.node-version }}
 
-      - name: Install Dependencies
-        run: |
-          npm install
-          npm install @eslint/eslintrc  # Include only if ESLint is needed during build
+    - name: Install dependencies 
+      run: |
+        npm install
+        npm install @eslint/eslintrc
 
-      - name: Build Project
-        run: |
-          npx webpack
+    - name: Build
+      run: |
+        npx webpack
