separate steps for eslint 3

diff --git a/.github/workflows/webpack.yml b/.github/workflows/webpack.yml
--- a/.github/workflows/webpack.yml
+++ b/.github/workflows/webpack.yml
@@ -30,11 +30,6 @@ jobs:
           npx eslint . -f json -o eslint-report.json || true  # Always return success
         continue-on-error: true
 
-      - name: Run ESLint 
-        run: | 
-          npx eslint . || true  # Prevent ESLint errors from failing the step
-        continue-on-error: true  # Ensure the job continues even if ESLint finds errors
-          
       - name: Upload ESLint Report
         uses: actions/upload-artifact@v3
         with:
@@ -42,6 +37,12 @@ jobs:
           path: eslint-report.json
           if-no-files-found: ignore
           include-hidden-files: false
+          
+      - name: Run ESLint 
+        run: | 
+          npx eslint . || true  # Prevent ESLint errors from failing the step
+        continue-on-error: true  # Ensure the job continues even if ESLint finds errors
+          
 
   build:
     name: Build with Node.js ${{ matrix.node-version }}
